In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
x=torch.tensor([4,4,5])

In [4]:
x

tensor([4, 4, 5])

In [5]:
x.ndim

1

In [6]:
x*3

tensor([12, 12, 15])

In [7]:
X=torch.tensor([1,3,4,7])

In [8]:
X

tensor([1, 3, 4, 7])

In [9]:
X.shape

torch.Size([4])

In [10]:
X.ndim

1

In [11]:
X=torch.tensor([[[1,3,4],
                 [8,7,5],
                 [1,5,3]]])

In [12]:
X.shape

torch.Size([1, 3, 3])

In [13]:
X.ndim

3

In [14]:
X[0][0][[1]]

tensor([3])

In [15]:
X=torch.zeros(2,2)

In [16]:
X

tensor([[0., 0.],
        [0., 0.]])

In [18]:
X=torch.ones(5,5,5,5)

In [19]:
X

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1.,

In [20]:
X=torch.rand(3,3)

In [21]:
X

tensor([[0.1104, 0.4864, 0.0710],
        [0.1763, 0.1743, 0.6626],
        [0.3519, 0.8899, 0.5548]])

In [22]:
X.dtype

torch.float32

In [23]:
X=torch.rand(3,3)

In [24]:
X

tensor([[0.4078, 0.7781, 0.9550],
        [0.8071, 0.5607, 0.0887],
        [0.5154, 0.9527, 0.3034]])

In [25]:
y=torch.ones_like(input=X)

In [26]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
y.dtype

torch.float32

In [29]:
X

tensor([[0.4078, 0.7781, 0.9550],
        [0.8071, 0.5607, 0.0887],
        [0.5154, 0.9527, 0.3034]])

In [58]:
y=y.type(torch.float32)

In [59]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [60]:
ans=y*X

In [61]:
ans.dtype

torch.float32

In [67]:
int_tensor=torch.ones_like(input=y,dtype=torch.float32)

In [68]:
int_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [69]:
anss=int_tensor*X

In [70]:
anss.dtype

torch.float32

In [71]:
MATRIX=torch.tensor([[1,3],
                    [4,6]])

In [72]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [73]:
MATRIX*MATRIX

tensor([[ 1,  9],
        [16, 36]])

In [74]:
ans=torch.matmul(MATRIX,MATRIX)

In [75]:
ans

tensor([[13, 21],
        [28, 48]])

In [76]:
ans.T

tensor([[13, 28],
        [21, 48]])

In [77]:
ans.dtype

torch.int64

In [79]:
ans.dtype

torch.int64

In [80]:
a=torch.tensor([2])

In [82]:
a.dtype

torch.int64

In [83]:
a=torch.tensor([2,3],dtype=torch.float32)

In [85]:
a.dtype


torch.float32

In [86]:
ans=MATRIX*MATRIX*MATRIX

In [87]:
ans.dtype

torch.int64

In [88]:
a*a

tensor([4., 9.])

In [89]:
a.dtype

torch.float32

In [94]:
MATRIX.type(torch.float32).mean()

tensor(3.5000)

In [95]:
MATRIX.sum()

tensor(14)