In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
x=torch.tensor([4,4,5])

In [4]:
x

tensor([4, 4, 5])

In [5]:
x.ndim

1

In [6]:
x*3

tensor([12, 12, 15])

In [7]:
X=torch.tensor([1,3,4,7])

In [8]:
X

tensor([1, 3, 4, 7])

In [9]:
X.shape

torch.Size([4])

In [10]:
X.ndim

1

In [11]:
X=torch.tensor([[[1,3,4],
                 [8,7,5],
                 [1,5,3]]])

In [12]:
X.shape

torch.Size([1, 3, 3])

In [13]:
X.ndim

3

In [14]:
X[0][0][[1]]

tensor([3])

In [15]:
X=torch.zeros(2,2)

In [16]:
X

tensor([[0., 0.],
        [0., 0.]])

In [17]:
X=torch.ones(5,5,5,5)

In [18]:
X

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1.,

In [19]:
X=torch.rand(3,3)

In [20]:
X

tensor([[0.2971, 0.9346, 0.9154],
        [0.0425, 0.5486, 0.7291],
        [0.7600, 0.0181, 0.5538]])

In [21]:
X.dtype

torch.float32

In [22]:
X=torch.rand(3,3)

In [23]:
X

tensor([[0.0459, 0.0777, 0.8262],
        [0.8790, 0.1404, 0.8825],
        [0.5168, 0.7025, 0.6947]])

In [24]:
y=torch.ones_like(input=X)

In [25]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
y.dtype

torch.float32

In [27]:
X

tensor([[0.0459, 0.0777, 0.8262],
        [0.8790, 0.1404, 0.8825],
        [0.5168, 0.7025, 0.6947]])

In [28]:
y=y.type(torch.float32)

In [29]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [30]:
ans=y*X

In [31]:
ans.dtype

torch.float32

In [32]:
int_tensor=torch.ones_like(input=y,dtype=torch.float32)

In [33]:
int_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [34]:
anss=int_tensor*X

In [35]:
anss.dtype

torch.float32

In [36]:
MATRIX=torch.tensor([[1,3],
                    [4,6]])

In [37]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [38]:
MATRIX*MATRIX

tensor([[ 1,  9],
        [16, 36]])

In [39]:
ans=torch.matmul(MATRIX,MATRIX)

In [40]:
ans

tensor([[13, 21],
        [28, 48]])

In [41]:
ans.T

tensor([[13, 28],
        [21, 48]])

In [42]:
ans.dtype

torch.int64

In [43]:
ans.dtype

torch.int64

In [44]:
a=torch.tensor([2])

In [45]:
a.dtype

torch.int64

In [46]:
a=torch.tensor([2,3],dtype=torch.float32)

In [47]:
a.dtype


torch.float32

In [48]:
ans=MATRIX*MATRIX*MATRIX

In [49]:
ans.dtype

torch.int64

In [50]:
a*a

tensor([4., 9.])

In [51]:
a.dtype

torch.float32

In [52]:
MATRIX.type(torch.float32).mean()

tensor(3.5000)

In [53]:
MATRIX.sum()

tensor(14)

In [54]:
import torch

In [55]:
X=torch.ones(10)

In [56]:
X

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
X.shape


torch.Size([10])

In [58]:
X.reshape(2,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [59]:
X.ndim

1

In [60]:
X.reshape(10,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [61]:
X.shape  # shape is not fuction it is a attribute

torch.Size([10])

In [62]:
X.ndim

1

In [63]:
y=torch.zeros(10)

In [64]:
y

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
y=y.reshape(5,2)

In [66]:
y.ndim

2

In [67]:
y=y.reshape(2,5)

In [68]:
x=y.view(1,10)

In [69]:
y

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [70]:
x[0][0]=43

In [71]:
y[0][0]

tensor(43.)

In [72]:
y.dtype

torch.float32

squeezesd

In [73]:
X=torch.tensor([1,2,3,4])

In [74]:
X.shape

torch.Size([4])

In [75]:
X=X.reshape(1,4)

In [76]:
X

tensor([[1, 2, 3, 4]])

In [77]:
X=X.squeeze()

In [78]:
X.shape

torch.Size([4])

In [79]:
X

tensor([1, 2, 3, 4])

Randn

In [80]:
X=torch.randn(2,3,4)

In [81]:
X

tensor([[[ 1.5705, -1.2692,  2.1047,  1.1882],
         [-0.0569,  0.5979,  1.7982,  0.7489],
         [ 1.1973, -1.4003,  1.2615, -0.0894]],

        [[ 1.0093, -0.4050, -0.1065,  0.3434],
         [ 0.1436, -2.7308,  0.6371,  1.8695],
         [-0.3259, -0.8834, -0.8259, -1.1167]]])

In [82]:
X=torch.permute(X,(2,1,0))

In [83]:
X

tensor([[[ 1.5705,  1.0093],
         [-0.0569,  0.1436],
         [ 1.1973, -0.3259]],

        [[-1.2692, -0.4050],
         [ 0.5979, -2.7308],
         [-1.4003, -0.8834]],

        [[ 2.1047, -0.1065],
         [ 1.7982,  0.6371],
         [ 1.2615, -0.8259]],

        [[ 1.1882,  0.3434],
         [ 0.7489,  1.8695],
         [-0.0894, -1.1167]]])

In [84]:
X=torch.rand(size=(256,256,3))

In [85]:
X

tensor([[[0.1891, 0.2283, 0.9087],
         [0.0399, 0.6827, 0.8445],
         [0.9469, 0.1577, 0.1383],
         ...,
         [0.2688, 0.0897, 0.5650],
         [0.9218, 0.6691, 0.7757],
         [0.6534, 0.6424, 0.5248]],

        [[0.3124, 0.4693, 0.0296],
         [0.1039, 0.2703, 0.3240],
         [0.3793, 0.1186, 0.0415],
         ...,
         [0.3420, 0.7693, 0.3121],
         [0.7054, 0.9769, 0.8577],
         [0.0392, 0.2045, 0.5587]],

        [[0.8345, 0.8326, 0.0546],
         [0.7876, 0.7394, 0.6873],
         [0.4888, 0.4369, 0.6193],
         ...,
         [0.2193, 0.5198, 0.9440],
         [0.8245, 0.3827, 0.7436],
         [0.0399, 0.8197, 0.9506]],

        ...,

        [[0.4295, 0.5450, 0.4609],
         [0.9691, 0.3131, 0.7078],
         [0.0741, 0.9992, 0.2755],
         ...,
         [0.7761, 0.5782, 0.9677],
         [0.1111, 0.8996, 0.5455],
         [0.5425, 0.8871, 0.3223]],

        [[0.9786, 0.7443, 0.3338],
         [0.8184, 0.6493, 0.7709],
         [0.

In [86]:
X[0][0][0]=5555

In [87]:
X[0][0][0]

tensor(5555.)

In [88]:
X_permute=X.permute(2,0,1)

In [89]:
X_permute[0][0][0]

tensor(5555.)

In [90]:
X=torch.arange(1,10)

In [91]:
X=X.reshape(1,3,3)

In [92]:
X

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [93]:
X[:,:,0]

tensor([[1, 4, 7]])

In [94]:
X[:,2,2]

tensor([9])

In [95]:
import torch

In [96]:
X=torch.tensor([1,2,343,4,5,6])

pytorch and numpy

In [113]:
import torch,numpy as np

In [114]:
X=torch.ones(8)

In [115]:
X,X.dtype

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]), torch.float32)

In [124]:
X_arr=X.type(torch.int64).numpy()

In [125]:
X_arr,X_arr.dtype

(array([1, 1, 1, 1, 1, 1, 1, 1]), dtype('int64'))

In [126]:
arr=np.arange(1,10)

In [127]:
arr.dtype

dtype('int64')

In [135]:
arr_tensor=torch.from_numpy(arr).type(torch.float32)

In [136]:
arr_tensor.dtype

torch.float32

In [139]:
y=torch.tensor([32423525,235]).type(torch.float32)

In [140]:
y.dtype

torch.float32

In [141]:
v=torch.tensor([3,35])

In [142]:
v.dtype

torch.int64

RANDOM SEED 

In [144]:
torch.manual_seed(42)

In [145]:
torch.manual_seed(42)
X=torch.rand(3,3)

In [146]:
torch.manual_seed(42)
Y=torch.rand(3,3)

In [147]:
X==Y

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [148]:
X.dtype

torch.float32

ACCESSING GPU

In [149]:
torch.cuda.is_available()

True